apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubechat.fullname" . }}-auth
  labels:
    {{- include "kubechat.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.auth.jwt.secret | b64enc }}

---
{{- if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubechat.fullname" . }}-postgresql-external
  labels:
    {{- include "kubechat.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgresql.external.password | b64enc }}
{{- end }}

---
{{- if not .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubechat.fullname" . }}-redis-external
  labels:
    {{- include "kubechat.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.redis.external.password | b64enc }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubechat.fullname" . }}-audit
  labels:
    {{- include "kubechat.labels" . | nindent 4 }}
type: Opaque
data:
  encryption-key: {{ "dev-encryption-key-change-in-production" | b64enc }}

---
{{- if .Values.operator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubechat.fullname" . }}-operator-webhook-certs
  labels:
    {{- include "kubechat.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t  # Placeholder cert
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t  # Placeholder key
{{- end }}