{{- if .Values.operator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubechat.fullname" . }}-operator
  labels:
    {{- include "kubechat.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubechat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: operator
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "kubechat.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: operator
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubechat.operatorServiceAccountName" . }}
      securityContext:
        {{- toYaml .Values.operator.securityContext | nindent 8 }}
      containers:
      - name: operator
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag | default .Values.global.imageTag }}"
        imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
        command:
        - /operator
        env:
        - name: LOG_LEVEL
          value: {{ .Values.operator.env.LOG_LEVEL | default "info" | quote }}
        - name: ENABLE_WEBHOOKS
          value: {{ .Values.operator.env.ENABLE_WEBHOOKS | default "true" | quote }}
        - name: HEALTH_CHECK_PORT
          value: {{ .Values.operator.env.HEALTH_CHECK_PORT | default "8082" | quote }}
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "kubechat-operator"
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
        - name: webhook
          containerPort: 9443
          protocol: TCP
        resources:
          {{- toYaml .Values.operator.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.operator.securityContext | nindent 10 }}
        volumeMounts:
        - name: cert
          mountPath: /tmp/k8s-webhook-server/serving-certs
          readOnly: true
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ include "kubechat.fullname" . }}-operator-webhook-certs
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}