name: CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

#     - name: Set up Go
#       uses: actions/setup-go@v5
#       with:
#         go-version: '1.22'

#     - name: Download dependencies
#       run: go mod download

#     - name: Verify dependencies
#       run: go mod verify

#     - name: Build
#       run: go build -v ./...

#     - name: Run tests
#       run: go test -v ./...

#     - name: Run go vet
#       run: go vet ./...

#     - name: Run go fmt
#       run: |
#         if [ -n "$(gofmt -s -l .)" ]; then
#           echo "Go code is not formatted:"
#           gofmt -s -d .
#           exit 1
#         fi

#   docker:
#     runs-on: ubuntu-latest
#     needs: test
#     steps:
#     - uses: actions/checkout@v4

#     - name: Build Docker image
#       run: docker build -t kubechat-operator:test .

#   security:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4

#     - name: Run Gosec Security Scanner
#       uses: securecodewarrior/github-action-gosec@master
#       with:
#         args: './...'